stages:
  - build
  - test
  - deploy

variables:
  # Настройки для Docker Hub
  DOCKER_REGISTRY: docker.io
  DOCKER_HUB_USERNAME: ivanlab19911502
  DOCKER_IMAGE: $DOCKER_HUB_USERNAME/myapp
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  KUBE_NAMESPACE: production

# Сборка приложения и создание Docker образа
build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # Авторизация в Docker Hub
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    
    # Сборка образа
    - cd jcat
    - docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
    - docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest
    
    # Публикация образа в Docker Hub
    - docker push $DOCKER_IMAGE:$IMAGE_TAG
    - docker push $DOCKER_IMAGE:latest
  tags:
    - kubernetes

# Тестирование приложения
test:
  stage: test
  image: maven:3.8-openjdk-17-slim
  script:
    - cd jcat/backend
    - mvn test
  tags:
    - kubernetes

# Деплой в Kubernetes с использованием отдельных файлов манифестов
deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
    - kubectl config use-context $KUBE_CONTEXT
    
    # Создаем секрет для доступа к Docker Hub, если его еще нет
    - |
      kubectl create secret docker-registry dockerhub-secret \
        --docker-server=docker.io \
        --docker-username=$DOCKER_HUB_USERNAME \
        --docker-password=$DOCKER_HUB_PASSWORD \
        --docker-email=$GITLAB_USER_EMAIL \
        -n $KUBE_NAMESPACE \
        --dry-run=client -o yaml | kubectl apply -f -
    
    # Заменяем переменные в манифестах перед применением
    - sed -i "s|__IMAGE_NAME__|$DOCKER_IMAGE:$IMAGE_TAG|g" jcat_k8s/Deployment_jcat.yaml
    - sed -i "s|__NAMESPACE__|$KUBE_NAMESPACE|g" jcat_k8s/*.yaml
    - sed -i "s|__REGISTRY_SECRET__|dockerhub-secret|g" jcat_k8s/Deployment_jcat.yaml
  script:
    # Создаем namespace, если он не существует
    - kubectl create namespace $KUBE_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    
    # Применяем секреты и ConfigMaps
    - kubectl apply -f jcat_k8s/postgres-credentials.yaml
    - kubectl apply -f jcat_k8s/init-db-script-cm.yaml
    
    # Применяем PVC для PostgreSQL
    - kubectl apply -f jcat_k8s/pvc_postgres.yaml
    
    # Деплоим PostgreSQL
    - kubectl apply -f jcat_k8s/Deployment_postgres.yaml
    - kubectl apply -f jcat_k8s/Service_postgres.yaml
    
    # Деплоим приложение
    - kubectl apply -f jcat_k8s/Deployment_jcat.yaml
    - kubectl apply -f jcat_k8s/Service_jcat.yaml
    
    # Проверка успешности деплоя
    - kubectl rollout status deployment/jcat -n $KUBE_NAMESPACE
  only:
    - master
  tags:
    - kubernetes