apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-rb
  namespace: gitlab
data:
  gitlab_omnibus_config: |
    external_url "#{ENV['GITLAB_URL']}"
    gitlab_rails['initial_root_password'] = "#{ENV['GITLAB_ROOT_PASSWORD']}"
    postgresql['enable'] = false
    gitlab_rails['db_adapter'] = "#{ENV['DB_ADAPTER']}"
    gitlab_rails['db_encoding'] = "#{ENV['DB_ENCODING']}"
    gitlab_rails['db_host'] = "#{ENV['DB_HOST']}"
    gitlab_rails['db_port'] = "#{ENV['DB_PORT']}"
    gitlab_rails['db_username'] = "#{ENV['DB_USERNAME']}"
    gitlab_rails['db_password'] = "#{ENV['DB_PASSWORD']}"
    gitlab_rails['db_database'] = "#{ENV['DB_DATABASE']}"