apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
spec:
  rules:
    - host: git-lab.devlaba.online
      http:
        paths:
          - path: /
            backend:
              serviceName: gitlab
              servicePort: 80

