apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab
  namespace: prod
spec:
  capacity:
    storage: 10Gi
    accessModes: 
      - ReadWriteOnce
    hostPath:
      path: /data/gitlab

-----------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab
spec:
  accessModes:
    -ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
