apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab_ce-gitlab-pv
  namespace: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /data/gitlab

-----------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab_ce-gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    -ReadWriteOnce
  resources:
    requests:
      storage: 20Gi


