apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-gitlab-pv
  namespace: gitlab
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres/postgres-gitlab
  
-------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
