apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv_gitlab
  namespace: prod
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
  
-------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc_gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
