apiVersion: v1
kind: Secret
metadata:
  name: secret-for-posetgres-gitlab
  namespace: gitlab
type: Opaque
data:
  postgres-password: 123      
  gitlab-root-password: 12345
  gitlab-url: https://git-lab.devlab.online 
  db_adapter: postgresql
  db_encoding: unicode
  db_host: postgres
  db_port: 5432
  db_username: gitlab
  db_database: gitlab_production

