apiVersion: v1
kind: Secret
metadata:
  name: secret-for-posetgres
  namespace: gitlab
type: Opaque
data:
  postgres-password: cG9zdGdyZXMxMjM=       # coding Base64 for postgres


apiVersion: v1
kind: Secret
metadata:
  name: secret-for-gitlab-url
  namespace: gitlab
type: Opaque
data:
  gitlab-url: aHR0cHM6Ly9naXQtbGFiLmRldmxhYmEu b25saW5l       # coding Base64 for gitlab url

