apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  ports:
  - port: 80                              # Порт, на котором сервис будет слушать 
    targetPort: 80                        # Порт, на который сервис будет перенаправлять трафик к подам
  selector:
    app: gitlab
