apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: prod
spec:
  serviceName: gitlab
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitalab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        env:
        - name: GITLAB_CONFIG
          value: |
            external_url 'https://git-lab.devlaba.online'          # host for connetction gitlab
            gitlab_rails['db_adapter'] = 'postgresql'
            gitlab_rails['db_encoding'] = 'unicode'
            gitlab_rails['db_host'] = 'postgres'
            gitlab_rails['db_port'] = '5432'
            gitlab_rails['db_username'] = 'gitlab'
            gitlab_rails['db_password'] = '<%= ENV["POSTGRES_PASSWORD"] %>'  # Password coding Base64 from postgres
            gitlab_rails['db_database'] = 'gitlab_production'
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-for-posetgres
                key: postgres-password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: gitlab-storage
          mountPath: /var/opt/gitlab
      volumes:
      - name: gitlab-storage
        persistentVolumeClaim:
          claimName: gitlab-pvc
