apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres_gitlab
  namespace: gitlab
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17.2
        env:
        - name: POSTGRES_USER
          value: gitlab
        - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-for-posetgres
                key: postgres-password  
        - name: POSTGRES_DB
          value: gitlab_production
         resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-gitlab-pvc
