apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: gitlab
spec:
  serviceName: "gitlab_ce"
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitalab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:17.6.4
        env:                                              
        # # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: gitlab-rb
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: gitlab-root-password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: postgres-password
        - name: GITLAB_URL
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: gitlab-url
        - name: DB_ADAPTER
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: db_adapter
        - name: DB_ENCODING
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: db_encoding
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: db_port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: db_username
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret-for-posetgres-gitlab
              key: db_database 
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: gitlab-storage
          mountPath: /var/opt/gitlab
        - name: gitlab-etc
          mountPath: /etc/gitlab
        - name: gitlab-data
          mountPath: /gitlab-data
        - name: gitlab-log
          mountPath: /var/log/gitlab
      volumes:
      - name: gitlab-storage
        persistentVolumeClaim:
          claimName: gitlab_ce-gitlab-pvc
