apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab
data:
  config.toml: |
    concurrent = 10
    check_interval = 30
    
    [[runners]]
      name = "Kubernetes Runner"
      url = "http://git-lab.devlaba.online"
      executor = "kubernetes"
      token = "glrt-81kxxkQRkXevquNJXSPs"
      [runners.kubernetes]
        namespace = "gitlab"
        image = "ubuntu:20.04"
        privileged = true