apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-replica
  namespace: gitlab
data:
  redis.conf: |+
    masterauth  Securep@55Here
    replicaof redis-master 6379
    replica-read-only yes
    replica-serve-stale-data yes