# ConfigMap for settings PostgreSQL
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-config
  namespace: gitlab
data:
  postgresql.conf: |
    # WAL config
    wal_level = replica  
    max_wal_size = 1GB        # Maximum size of WAL files before automatic cleaning
    min_wal_size = 80MB       # Min size of WAL files 
    wal_keep_segments = 32    # Number of WAL files to be saved
    
    # setting replica
    max_wal_senders = 10         
    max_replication_slots = 10
    
    # setting performance
    shared_buffers = 256MB
    effective_cache_size = 1GB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    
    # setting reliability
    synchronous_commit = on
    full_page_writes = on