apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-master-gitlab-pv
  namespace: gitlab
spec:
  storageClassName: local
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/postgres-master-gitlab
  nodeAffinity:  
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2
     
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-replica-gitlab-pv
  namespace: gitlab
spec:
  storageClassName: local
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/postgres-replica-gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node3
     

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi