apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-master-gitlab-pv
  namespace: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/postgres-master-gitlab
     
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-replica-gitlab-pv
  namespace: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/postgres-replica-gitlab
     

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi