apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-gitlab-pv
  namespace: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres/postgres_master-gitlab
  
-------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres_master-gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

-------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres_replica-gitlab-pv
  namespace: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres/postgres_replica-gitlab 

-------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres_replica-gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
