apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: gitlab
spec:
  type: ClusterIP
  ports:
  - port: 5432                              # The port on which the service will listen 
    targetPort: 5432                        # The port to which the service will redirect traffic to the pods
  selector:
    app: postgres
    role: replica

