apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master_gitlab
  namespace: gitlab
spec:
  serviceName: "postgres-master"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: master
  template:
    metadata:
      labels:
        app: postgres
        role: master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - postgres
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: postgres
        image: postgres:17.2
        env:
        - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-for-posetgres-gitlab
                key: db_username  
        - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-for-posetgres-gitlab
                key: postgres-password
        - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: secret-for-posetgres-gitlab
                key: db_database
        - name: REPLICATION_MODE
            value: "master"
         resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres_master-gitlab-pvc
      - name: postgres-config
        configMap:
          name: postgres-master-config
